// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYRf1halN-JVwx1PwHCqvAcB0UeecEDlI',
    appId: '1:1043853491459:web:68fe909550a22915f6bd36',
    messagingSenderId: '1043853491459',
    projectId: 'alletre-auctions',
    authDomain: 'alletre-auctions.firebaseapp.com',
    storageBucket: 'alletre-auctions.firebasestorage.app',
    measurementId: 'G-JP9K1Z75DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgbclpNusftI8wyGVLOKtviWHperC9Mc',
    appId: '1:1043853491459:android:54cb3c69b44ac184f6bd36',
    messagingSenderId: '1043853491459',
    projectId: 'alletre-auctions',
    storageBucket: 'alletre-auctions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__JBXQY6br0wKBGFr1I65Rck2FeF05mI',
    appId: '1:1043853491459:ios:8bd70f2a36ca6fb7f6bd36',
    messagingSenderId: '1043853491459',
    projectId: 'alletre-auctions',
    storageBucket: 'alletre-auctions.firebasestorage.app',
    androidClientId: '1043853491459-2ntuv0c6mp761tuk8f1hb78ilp746pg0.apps.googleusercontent.com',
    iosClientId: '1043853491459-gqe7h7h4cg9omdsoaag5qm0pubu5lsru.apps.googleusercontent.com',
    iosBundleId: 'com.example.alletreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__JBXQY6br0wKBGFr1I65Rck2FeF05mI',
    appId: '1:1043853491459:ios:8bd70f2a36ca6fb7f6bd36',
    messagingSenderId: '1043853491459',
    projectId: 'alletre-auctions',
    storageBucket: 'alletre-auctions.firebasestorage.app',
    androidClientId: '1043853491459-2ntuv0c6mp761tuk8f1hb78ilp746pg0.apps.googleusercontent.com',
    iosClientId: '1043853491459-gqe7h7h4cg9omdsoaag5qm0pubu5lsru.apps.googleusercontent.com',
    iosBundleId: 'com.example.alletreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYRf1halN-JVwx1PwHCqvAcB0UeecEDlI',
    appId: '1:1043853491459:web:e3b0bb79d32e42aef6bd36',
    messagingSenderId: '1043853491459',
    projectId: 'alletre-auctions',
    authDomain: 'alletre-auctions.firebaseapp.com',
    storageBucket: 'alletre-auctions.firebasestorage.app',
    measurementId: 'G-F5DR7DJTQ8',
  );
}
